
title: "F. Nebulous Exists"
email: "your-email@example.com"
twitter: "fnebex"
soundcloud: "fnebex"
instagram: "fnebex"
description: "Sample based producer from Buffalo, NY with some samplers and things to go beep boop. GameBoy enthusiest and anime lover. You probablly hate DitF for the wrong reasons."


plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
